# Generated by Django 5.2.7 on 2025-10-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_ID', models.CharField()),
                ('gender', models.CharField()),
                ('nationality', models.CharField()),
                ('birth_date', models.DateField()),
                ('telephone', models.CharField()),
                ('address', models.CharField()),
            ],
        ),
    ]
