# Generated by Django 5.2.7 on 2025-10-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_incity_outcity_delete_incities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('depart_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('travel_time', models.TimeField()),
                ('airline', models.CharField()),
                ('flight_number', models.CharField()),
                ('cabin_class', models.CharField()),
                ('remaining_capacity', models.PositiveIntegerField()),
                ('allowed_loggage', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('origin_airport', models.CharField()),
                ('dest_airport', models.CharField()),
                ('airplane_model', models.CharField()),
                ('flight_law', models.TextField()),
                ('price_detail', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='OutCity',
        ),
        migrations.RenameModel(
            old_name='InCity',
            new_name='City',
        ),
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.ManyToManyField(related_name='destinations', to='flights.city'),
        ),
        migrations.AddField(
            model_name='flight',
            name='origin',
            field=models.ManyToManyField(related_name='origins', to='flights.city'),
        ),
    ]
