# Generated by Django 5.2.7 on 2025-10-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flight_delete_outcity_rename_incity_city_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flight',
            new_name='Ticket',
        ),
    ]
