# Generated by Django 5.2.7 on 2025-10-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_rename_flight_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='airline',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='airplane_model',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='allowed_loggage',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='arrival_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cabin_class',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='depart_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dest_airport',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='flight_law',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='flight_number',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='origin_airport',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='remaining_capacity',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='travel_time',
            field=models.TimeField(blank=True),
        ),
    ]
