# Generated by Django 5.2.7 on 2025-10-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_alter_ticket_airline_alter_ticket_airplane_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='depart_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='travel_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
