# Generated by Django 5.2.7 on 2025-10-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_alter_ticket_arrival_time_alter_ticket_depart_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='allowed_loggage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='remaining_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
