# Generated by Django 5.2.7 on 2025-10-12 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_alter_ticket_allowed_loggage_alter_ticket_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='origin',
        ),
        migrations.AddField(
            model_name='ticket',
            name='destination',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='flights.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='origin',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, related_name='origins', to='flights.city'),
            preserve_default=False,
        ),
    ]
