# Generated by Django 5.2.7 on 2025-10-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_remove_ticket_destination_remove_ticket_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='Type',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
    ]
