# Generated by Django 5.2.7 on 2025-10-14 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0011_alter_city_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='Type',
        ),
    ]
