# Generated by Django 5.2.7 on 2025-10-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0012_remove_city_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='Type',
            field=models.CharField(null=True),
        ),
    ]
