# Generated by Django 5.2.7 on 2025-10-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0013_city_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='Type',
            field=models.CharField(blank=True, null=True),
        ),
    ]
