# Generated by Django 5.2.7 on 2025-10-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0014_alter_city_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='Type',
        ),
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.CharField(blank=True, null=True),
        ),
    ]
