# Generated by Django 5.2.7 on 2025-10-18 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0015_remove_city_type_ticket_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('passengers', models.TextField()),
                ('fligt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flights.ticket')),
            ],
        ),
    ]
