# Generated by Django 5.2.7 on 2025-10-18 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0016_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fligt_id',
            new_name='flight_id',
        ),
    ]
