# Generated by Django 5.2.7 on 2025-10-18 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0017_rename_fligt_id_order_flight_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('national_id', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='airline',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='airplane_model',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cabin_class',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dest_airport',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='flight_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='origin_airport',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='flights.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('passengers', models.ManyToManyField(to='flights.passenger')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
