# Generated by Django 5.2.7 on 2025-10-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0018_passenger_alter_ticket_airline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='airplane_model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dest_airport',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='origin_airport',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
