# Generated by Django 5.2.7 on 2025-11-02 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0019_alter_ticket_airplane_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='allowed_loggage',
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='allowed_luggage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='CityName',
            field=models.CharField(max_length=10),
        ),
    ]
