# Generated by Django 5.2.7 on 2025-11-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0020_remove_ticket_allowed_loggage_booking_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='travel_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
