# Generated by Django 5.2.7 on 2025-11-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0021_alter_ticket_travel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
