# Generated by Django 5.2.7 on 2025-11-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0022_alter_booking_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='travel_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
