# Generated by Django 5.2.7 on 2025-11-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0024_alter_booking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='type',
            field=models.CharField(blank=True, choices=[('IN', 'Inner City'), ('OUT', 'Foreign City')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(blank=True, choices=[('IN', 'Inner City'), ('OUT', 'Foreign City')], max_length=20, null=True),
        ),
    ]
