# Generated by Django 5.2.7 on 2025-11-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0025_city_type_alter_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='type',
            field=models.CharField(choices=[('IN', 'Inner City'), ('OUT', 'Foreign City')], max_length=20),
        ),
    ]
