# Generated by Django 5.2.7 on 2025-11-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0026_alter_city_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tracking_number',
            field=models.CharField(default='490627e8', editable=False, unique=True),
        ),
    ]
