# Generated by Django 5.2.7 on 2025-11-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0027_booking_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tracking_number',
            field=models.UUIDField(default='4fc33ecf', editable=False, unique=True),
        ),
    ]
