# Generated by Django 5.2.7 on 2025-11-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0028_alter_booking_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tracking_number',
            field=models.CharField(default='3a837718', editable=False, unique=True),
        ),
    ]
