# Generated by Django 5.2.7 on 2025-11-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0029_alter_booking_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tracking_number',
            field=models.CharField(),
        ),
    ]
