# Generated by Django 5.2.7 on 2025-11-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0030_alter_booking_tracking_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tracking_number',
        ),
    ]
