# Generated by Django 5.2.7 on 2025-11-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0031_remove_booking_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tracking_number',
            field=models.CharField(blank=True, default='9b6657ee', editable=False, null=True, unique=True),
        ),
    ]
