# Generated by Django 5.2.7 on 2025-11-09 07:12

import flights.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0034_alter_booking_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tracking_number',
            field=models.CharField(default=flights.models.Booking.generate_tracking_number, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(blank=True, choices=[('IN', 'Domestic Flight'), ('OUT', 'Foreign Flight')], max_length=20, null=True),
        ),
    ]
