# Generated by Django 5.2.7 on 2026-01-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0035_alter_booking_tracking_number_alter_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='arrival_time',
            field=models.TimeField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='depart_time',
            field=models.TimeField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='travel_time',
            field=models.TimeField(blank=True, max_length=5, null=True),
        ),
    ]
