# Generated by Django 5.2.7 on 2026-01-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0036_alter_ticket_arrival_time_alter_ticket_depart_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='arrival_time',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='depart_time',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='travel_time',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
