# Generated by Django 5.2.7 on 2026-01-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0037_alter_ticket_arrival_time_alter_ticket_depart_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.CharField(blank=True, null=True),
        ),
    ]
