# Generated by Django 5.2.7 on 2026-01-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0038_alter_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
