# Generated by Django 5.2.7 on 2026-01-25 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0039_alter_ticket_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
    ]
